In [ ]:
import os
# from quickda.explore_data import *
# from quickda.clean_data import *
# from quickda.explore_numeric import *
# from quickda.explore_categoric import *
# from quickda.explore_numeric_categoric import *
# from quickda.explore_time_series import *
import pandas as pd
import numpy as np

In [ ]:
import os
import pandas as pd
import numpy as np
df = pd.read_csv("../data/seattle_house_price/clean_seattle_price_reg_train.csv")


# # to_datetime = 'dt_applied'
# # to_categoric = ['delinq_2yrs', 'inq_last_6mths', 'loan_writeoff', 'pub_rec']

# df = df.astype({"Year": str, "zip_code":str})
# df.fillna(method = 'ffill', inplace=True)
#

In [ ]:
#df.drop_duplicates(inplace=True)
df.drop_duplicates(subset = ["Major", "Minor", "DocumentDate"], inplace=True)

In [ ]:
df.drop(columns=['Unnamed: 0', "ZipCode", "WaterSystem", "SewerSystem", "Access", "TrafficNoise", "AirportNoise", "PowerLines", "WaterProblems", "YrRenovated"], inplace = True)

In [ ]:
df = df[(df["SqFtLot"] <=47862.6) & (df['SalePrice'] <= 9944196.8) ]### 95% quantile for sqftlot and 99.98% quantile for saleprice.

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
#explore(df, method = "profile", report_name="seattle_reg_report", is_large_dataset=False)

In [ ]:
from pycaret.regression import *

In [ ]:
df.tail(1)

In [ ]:
#, 'mobiluty_abroad', 'mobility_withincounty', 'mobility_withinstate', 'mobility_withUS
df['unemployment'] = df['unemployment'].str[:-1].astype(float)/100
df['mobility_abroad'] = df['mobility_abroad'].str[:-1].astype(float)/100
df['mobility_county'] = df['mobility_county'].str[:-1].astype(float)/100
df['mobility_state'] = df['mobility_state'].str[:-1].astype(float)/100
df['mobility_us'] = df['mobility_us'].str[:-1].astype(float)/100
df.head(1)

In [11]:
demo = setup(data = df, target = 'SalePrice', 
                   ignore_features = ['Major','Minor','DocumentDate'], normalize = True,
                   transformation= False, transformation_method = 'yeo-johnson', 
                   categorical_features = ['HouseType', 'HeatSystem', 'HeatSource',], numeric_features=['Stories', 'BldgGrade','Bedrooms', 'Bathrooms','Condition','YrBuilt','30FixedMortgage', 'stockDGL', 'stockQQQ', 'stockSPY', 'Inflation_Rate',
       'unemployment', 'median_income', 'mobility_county', 'mobility_state',
       'mobility_us', 'mobility_abroad'],
                   transform_target = True, remove_outliers= False, 
                   remove_multicollinearity = True,
                   ignore_low_variance = True, combine_rare_levels = True)

In [12]:
best_model = compare_models()

In [ ]:
et = create_model('et')

In [ ]:
plot_model(et)